---
title: "Exploration"
output: html_document
---

# Lyft Data Exploration

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Libraries

```{r}
library(tidyverse)
library(gridExtra)
library(lme4)
```

## Load Data and Format

```{r}
data = read_csv("CleanLyftData.csv", col_types = cols())

data$DOW = factor(data$DOW, levels = seq(1,7), labels = c("Mon", "Tue", "Wed", "Thur", "Fri", "Sat", "Sun"))
data$Month = factor(data$Month, levels = seq(1,12), labels = seq(1,12))
data$StartLocation = factor(data$StartLocation)
data$Period = factor(data$Period)
data$Movement = factor(data$Movement)
data$Origin = factor(data$Origin)
data$Goal = factor(data$Goal)
```

```{r}
# create a new dataframe
result = NULL

# iterate over each session (necessary for knowing the first and last rides of a session)
for (session in unique(data$Session)) {
  
  # get only periods for this session
  s = data[data$Session == session, ]
  
  # create a few new columsn of interest
  # these better explain how much effort is put into a ride
  s$AdjDuration = NA
  s$AdjDistance = NA
  s$AdjGas = NA
  
  # get the indices of periods which were actual drives. We'll modify and keep these rows
  w = which(s$Period == "Drive")
  # iterate over each drive index
  for (ix in 1:length(w)) {
    # if this is the first drive in the session:
    if (ix == 1) {
      # get the indices of any periods which came before this drive
      pre = head(seq(1, w[ix]), -1)
      # get the indices of any periods which came after this drive (but not after the next drive)
      post = tail(seq(w[ix], w[ix+1]-1), -1)
      
      adj_dr = s[w[ix], "Duration"] + sum(s[pre, "Duration"]) + sum(s[post, "Duration"]) / 2
      adj_ds = s[w[ix], "Distance"] + sum(s[pre, "Distance"]) + sum(s[post, "Distance"]) / 2
      adj_gs = s[w[ix], "GasUsage"] + sum(s[pre, "GasUsage"]) + sum(s[post, "GasUsage"]) / 2
      
    } else if (ix == max(1:length(w))) {
      # if this is the last drive in the session:
      
      # get the indices of any periods which came before this drive (but not before the drive prior)
      pre = head(seq(w[ix-1]+1, w[ix]), -1)
      # get the indices of any periods which came after this drive (until the end of the session)
      post = tail(seq(w[ix], nrow(s)), -1)
      
      adj_dr = s[w[ix], "Duration"] + sum(s[pre, "Duration"]) / 2 + sum(s[post, "Duration"])
      adj_ds = s[w[ix], "Distance"] + sum(s[pre, "Distance"]) / 2 + sum(s[post, "Distance"])
      adj_gs = s[w[ix], "GasUsage"] + sum(s[pre, "GasUsage"]) / 2 + sum(s[post, "GasUsage"])

    } else {
      # if this is neither the first nor the last drive in the session:
      
      # get the indices of any periods which came before this drive (but not before the drive prior)
      pre = head(seq(w[ix-1]+1, w[ix]), -1)
      # get the indices of any periods which came after this drive (but not after the next drive)
      post = tail(seq(w[ix], w[ix+1]-1), -1)
      
      # the new columns take into account the context of the surrounding periods
      # each drive takes responsibility for how much driving is neccessary to get to it and to get to the next drive
      adj_dr = s[w[ix], "Duration"] + sum(s[pre, "Duration"]) / 2 + sum(s[post, "Duration"]) / 2
      adj_ds = s[w[ix], "Distance"] + sum(s[pre, "Distance"]) / 2 + sum(s[post, "Distance"]) / 2
      adj_gs = s[w[ix], "GasUsage"] + sum(s[pre, "GasUsage"]) / 2 + sum(s[post, "GasUsage"]) / 2
      
    }
    # append data to our new columns
    s[w[ix], "AdjDuration"] = adj_dr
    s[w[ix], "AdjDistance"] = adj_ds
    s[w[ix], "AdjGas"] = adj_gs
  }
  
  # save the session into our new dataframe
  result = rbind(result, s[w, ])
}

result = mutate(result, AdjWage = (Earnings + Tips) * (60 / AdjDuration))
```

```{r}
gasPrice = 3.45 # $ / gal
```

### Preview Data

```{r}
tail(result)
```

## Visualizations

```{r}
theme = theme_minimal()
```

### Wage Distribution

```{r}
avg = sum(result$Earnings + result$Tips) * (60/sum(result$AdjDuration))
gasInc = (result$Earnings + result$Tips - gasPrice * result$AdjGas) * (60/result$AdjDuration)
avgGasInc = sum(result$Earnings + result$Tips - gasPrice * result$AdjGas) * (60/sum(result$AdjDuration))

ggplot(result) + theme +
  geom_density(aes(AdjWage)) +
  geom_vline(xintercept = avg, lty=2) +
  geom_text(aes(avg, y = 0.1, label = paste("Mean: $", round(avg, 2), sep="")), nudge_x = 7) +
  geom_density(aes(gasInc), col="red") +
  geom_vline(xintercept = avgGasInc, col="red", lty=2) +
  geom_text(aes(avg, y = 0.1, label = paste("Mean: $", round(avgGasInc, 2), sep="")), nudge_x = -10) +
  lims(x=c(0,60)) +
  labs(title = "Wage Distribution")
```

```{r,}
p1 = ggplot(result, aes(PickupTime, AdjWage)) + theme +
  geom_point() +
  geom_smooth(method = "loess") +
  labs(title = "Adjusted Wage by Pickup Time")

p2 = ggplot(result) +
  geom_boxplot(aes(DOW, AdjWage)) +
  labs(title = "Adjusted Wage by Day of the Week")

grid.arrange(p1, p2, ncol=2)

ggplot(result) +
  geom_tile(aes(x = PickupTime, y = DOW, fill = AdjWage)) +
  labs(x = "Pickup Time", y = "Day of Week", fill = "Adjusted Wage", title = "Adjusted Wage per Day and Hour")
```

## Local Regression

```{r}
m1 = loess(AdjWage ~ PickupTime, 
          span = 0.5, 
          degree = 2, 
          data = result, 
          family = "gaussian")

m2 = loess(AdjWage ~ PickupTime, 
          span = 1.0, 
          degree = 2, 
          data = result, 
          family = "gaussian")

m3 = loess(AdjWage ~ PickupTime, 
          span = 0.5, 
          degree = 1, 
          data = result, 
          family = "gaussian")
```

```{r}
x = seq(5, 22, 0.1)

a1 = predict(m1, x)
a2 = predict(m2, x)
a3 = predict(m3, x)

ggplot() +
  geom_point(aes(result$PickupTime, result$AdjWage)) +
  geom_line(aes(x, a1), col="red") +
  geom_line(aes(x, a2), col="blue") +
  geom_line(aes(x, a3), col="purple")
```

```{r}
sum(data[data$Period != "Drive", ]$Duration) / sum(data$Duration)
sum(data[data$Period != "Drive", ]$Distance) / sum(data$Distance)
```


Gas-adjusted Hourly Wage

```{r}
(sum(data$Earnings + data$Tips) - sum(data$GasUsage) * gasPrice) * (60/sum(data$Duration))
```

## Determinants

```{r}
m = lmer(Wage ~ 1 + (1|Session), data = rideData)
summary(m)
```

```{r}
fixef(m)
ranef(m)
```


```{r}
ggplot(data) + geom_density(aes(Distance))
ggplot(data) + geom_density(aes(Duration))
```

